In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot

In [3]:
data = pd.read_csv("./data/train.csv")
data.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
# We want our dataset as a numpy array
data = np.array(data)
m, n = data.shape
np.random.shuffle(data)

# Separating our data as the development data and training data (type of cross-validation training)

data_dev = data[0:1000].T
Y_dev = data_dev[0] # label
X_dev = data_dev[1:n]

data_train = data[1000:m].T
Y_train = data_train[0] # label
X_train = data_train[1:n]

# Shuffling our data to prevent overfitting

In [10]:
def init_params():
    W1 = np.random.randn(10, 784)
    b1 = np.random.randn(10, 1)
    
    W2 = np.random.randn(10, 10) # previous layer has 10 perceptrons
    b2 = np.random.randn(10, 1) 
    
    return W1, b1, W2, b2

def ReLU(x):
    return np.maximum(0, x)

def softmax(Z):
    return np.exp(Z) / np.sum(np.exp(Z))

def forward_propagation(W1, b1, W2, b2, X):
    
    Z1 = W1 * X + b1
    A1 = ReLU(Z1)
    
    Z2 = W2 * A1 + b2
    A2 = softmax(Z2)
    
    return Z1, A1, Z2, A2

def one_hot(Y):
    one_hot_y = np.zeros((Y.size, Y.max() + 1) # Creates a matrix of zeros, Y.size rows and 10 spaces, for one-hot
    one_hot_y[np.arange(Y.size), Y] = 1 # for each row, go to column Y and place 1
    return one_hot_y.T # So it can be multiplied

                         

                         
def back_propagation(Z1, A1, Z2, A2, W2, Y):
    
    m = Y.size
    dZ2 = A2 - one_hot(Y)
    dW2 = (dZ2 * A1.T) / m
    dB2 = (np.sum(dZ2))/ m
    dZ1 = W2.T * dZ2